version: "3.3"

services:
  core:
    build:
      context: .
      dockerfile: apps/nitro/Dockerfile
    container_name: nitro
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    env_file:
      - apps/nitro/.env
